In [2]:
import numpy as np

##### 1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a Numpy array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return 
##### [
##### [5, 5, 5],
##### [5, 5, 5],
##### [5, 5, 5]
##### ]

In [3]:
def create_tuple(dim1,dim2,value):
    arr = np.full((dim1,dim2),value)
    return arr

In [4]:
create_tuple(3,3,5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

##### 2. Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.

In [5]:
# for total sum
a=np.array([10,20,30])
b=np.array([40,50,60])
np.sum([a,b])

210

In [6]:
# for column sum
a=np.array([10,20,30])
b=np.array([40,50,60])
np.sum([a,b],axis=0)

array([50, 70, 90])

##### 3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M. The method should return the top-left N X M sub matrix e.g:
##### [
##### [1, 2, 3],
##### [4, 5, 6],
##### [7, 8, 9],
##### ]
##### top_left_sub_matrix (matrix, 2, 2) -> should return:
##### [
##### [1, 2]
##### [4, 5]
##### ]

In [9]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
def sub_matrix(d_matrix,index1,index2):
    sub_mat = d_matrix[:index1,:index2]
    return sub_mat

In [12]:
sub_matrix(arr1,2,2)

array([[1, 2],
       [4, 5]])

##### 4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M The method should return the bottom-right N X M sub matrix e.g.:
##### [
##### [1, 2, 3],
##### [4, 5, 6],
##### [7, 8, 9],
##### ]
##### sub_matrix(matrix, 1, 1) -> should return : (Keep in mind these arrays are zero indexed)
##### [
##### [5, 6]
##### [8, 9]
##### ]

In [13]:
def sub_matrix1(d_matrix,index1,index2):
    sub_mat1 = d_matrix[index1:,index2:]
    return sub_mat1

In [14]:
sub_matrix1(arr1,1,1)

array([[5, 6],
       [8, 9]])

#### 5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values:
#### [1, 1, 1]
#### solution(arr) -> should return :
#### {'mean': 1.0, 'std_dev': 0.0}

In [19]:
arr1d = np.array([1,1,1])
arr1d

array([1, 1, 1])

In [44]:
def stat(arr1d):
    dict1 = {'mean' : np.mean(arr1d),'std_dev' : np.std(arr1d)}
    return dict1

In [49]:
dictionary = stat(arr1d)
dictionary

{'mean': 1.0, 'std_dev': 0.0}

In [48]:
type(dictionary)

dict