# 5 Interesting and Useful Numpy Functions

- numpy.diag(v,k=0)
- numpy.swapaxes(array, axis1, axis2)
- numpy.dsplit(arrayy, indices_or_sections)
- linalg.eig(array)
- np.arange(start,stop,step)

In [82]:
!pip install jovian --upgrade -q

In [83]:
import jovian

In [84]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anithabhukya/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anithabhukya/numpy-array-operations


'https://jovian.ai/anithabhukya/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [85]:
import numpy as np

# List of functions explained 

function1 = np.diag(v,k=0)

function2 = np.swapaxes(array,axis1,axis2)

function3 = numpy.dsplit(arrayy, indices_or_sections)

function4 = linalg.eig(array)

function5 = np.arange(start,stop,step)

## Function 1 - np.diag(v,k=0)

This array is used to extract a diagonal or construct a diagonal array.
v : array_like
If v is a 2-D array, return a copy of its k-th diagonal. If v is a 1-D array, return a 2-D array with v on the k-th diagonal.

k : int, optional
Diagonal in question. The default is 0. Use k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.

In [86]:
# Example 1 - working with a 1-D array

arr1 = np.random.randint(1,10,size = (5))
print(arr1)

[8 9 2 1 5]


In [87]:
# extracting a diagonal array out of 1-D array - returns a 2-D array with arr1 on mentioned kth diagonal(default = 0)

arr1d = np.diag(arr1) # ---------- OR --------- # arr1d = np.diag(arr1,k=0)

print(arr1d)

[[8 0 0 0 0]
 [0 9 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 5]]


In [88]:
# k>0 for diagonals above the main diagonal, and k<0 for diagonals below the main diagonal.
arrk1d = np.diag(arr1,k=-1)
print(arrk1d)

[[0 0 0 0 0 0]
 [8 0 0 0 0 0]
 [0 9 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 5 0]]


In [89]:
arrku1d = np.diag(arr1,k=1)
print(arrku1d)

[[0 8 0 0 0 0]
 [0 0 9 0 0 0]
 [0 0 0 2 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 5]
 [0 0 0 0 0 0]]


Explanation about example

In [90]:
# Example 2 - working with a 2-D array, return a copy of its k-th diagonal
arr2d = np.random.randint(1,20,size = (3,4))
print(arr2d)

[[ 2 13 13  8]
 [13 16 16  2]
 [ 6  4  6  9]]


In [91]:
# with k as default value = 0
np.diag(arr2d)

array([ 2, 16,  6])

In [92]:
# with k as value = -2
np.diag(arr2d,k = -2)

array([6])

In [93]:
# with k as value = 3
np.diag(arr2d,k = 3)

array([8])

The above function np.diag(v,k=0) works with a 1-D and 2-D array but does not work on 3-D arrays.

In [94]:
# Example 3 - breaking (to illustrate when it breaks)
arr3d = np.random.randint(1,20,size = (4,3,2))
print(arr3d)

[[[ 4 10]
  [12 10]
  [10 10]]

 [[14  2]
  [ 2  9]
  [ 6 14]]

 [[ 6 16]
  [ 9 15]
  [ 6 13]]

 [[ 7 13]
  [ 9  4]
  [18 13]]]


In [95]:
np.diag(arr3d)

ValueError: Input must be 1- or 2-d.

In [96]:
arr3d

array([[[ 4, 10],
        [12, 10],
        [10, 10]],

       [[14,  2],
        [ 2,  9],
        [ 6, 14]],

       [[ 6, 16],
        [ 9, 15],
        [ 6, 13]],

       [[ 7, 13],
        [ 9,  4],
        [18, 13]]])

In [97]:
np.diagonal(arr3d,axis1 = 1,axis2 = 2)

array([[ 4, 10],
       [14,  9],
       [ 6, 15],
       [ 7,  4]])

As said above numpy.diag can only be used for 1-D and 2-D arrays but an other function numpy.diagonal can be used for 3-D arrays.

The diag() function is used to extract a diagonal or construct a diagonal array.

In [98]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anithabhukya/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anithabhukya/numpy-array-operations


'https://jovian.ai/anithabhukya/numpy-array-operations'

## numpy.swapaxes(array,axis1,axis2)

Interchange two axes of an array.

In [99]:
# Example 1 - working on 2-D array
a1 = np.array([[1,2,3],[4,5,6]])
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
np.swapaxes(a1,0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])

numpy.swapaxes is applied to a 2-D array where 0 and 1 refers to first and 2nd axis respectively

In [101]:
# Example 2 - working on 3-D array
a2 = np.random.randint(1,10,size = (3,2,3))
a2

array([[[8, 9, 2],
        [5, 7, 7]],

       [[5, 6, 4],
        [5, 3, 9]],

       [[3, 6, 6],
        [5, 5, 3]]])

In [102]:
np.swapaxes(a2,0,2)

array([[[8, 5, 3],
        [5, 5, 5]],

       [[9, 6, 6],
        [7, 3, 5]],

       [[2, 4, 6],
        [7, 9, 3]]])

In [103]:
np.swapaxes(a2,1,2)

array([[[8, 5],
        [9, 7],
        [2, 7]],

       [[5, 5],
        [6, 3],
        [4, 9]],

       [[3, 5],
        [6, 5],
        [6, 3]]])

In [104]:
np.swapaxes(a2,0,1)

array([[[8, 9, 2],
        [5, 6, 4],
        [3, 6, 6]],

       [[5, 7, 7],
        [5, 3, 9],
        [5, 5, 3]]])

In the above example numpy.swapaxes is applied to 3-D array with interchange of axes in 3 different cells

In [105]:
# Example 3 - breaking (to illustrate when it breaks)
a3 = np.array([1,2,3,4,5,6])
a3

array([1, 2, 3, 4, 5, 6])

In [106]:
np.swapaxes(a3,0,1)

AxisError: axis2: axis 1 is out of bounds for array of dimension 1

In [107]:
a3 = np.array([1,2,3,4,5,6])
a4 = np.array([a3])
a4

array([[1, 2, 3, 4, 5, 6]])

In [108]:
np.swapaxes(a4,0,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

numpy.swapaxes does not work for 1-D arrays, hence a new 2-D array with the existing 1-D array can be created and numpy.swapaxes can be applied to the new 2-D array.

numpy.swapaxes can be used to interchange two axes of an array.

In [109]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anithabhukya/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anithabhukya/numpy-array-operations


'https://jovian.ai/anithabhukya/numpy-array-operations'

## Function 3 - numpy.dsplit(array, indices_or_sections)

Split array into multiple sub-arrays along the 3rd axis (depth).

In [110]:
# Example 1 - working
a3d = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a3d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [111]:
np.dsplit(a3d,2)

[array([[[ 1,  2],
         [ 5,  6]],
 
        [[ 9, 10],
         [13, 14]]]),
 array([[[ 3,  4],
         [ 7,  8]],
 
        [[11, 12],
         [15, 16]]])]

In the above example the 3-D array is split into sub-arrays with axis = 2

In [112]:
# Example 2 - working
a4d = np.random.randint(1,50,size=(2,2,2,2))
a4d

array([[[[45,  7],
         [ 5, 13]],

        [[32,  9],
         [16, 14]]],


       [[[49,  1],
         [42, 42]],

        [[ 7,  2],
         [41, 13]]]])

In [113]:
np.dsplit(a4d,2)

[array([[[[45,  7]],
 
         [[32,  9]]],
 
 
        [[[49,  1]],
 
         [[ 7,  2]]]]),
 array([[[[ 5, 13]],
 
         [[16, 14]]],
 
 
        [[[42, 42]],
 
         [[41, 13]]]])]

The above example is a 4-D array where np.dsplit splits the array into equal sub-arrays

In [114]:
# Example 3 - breaking (to illustrate when it breaks)
a2d = np.array([[1,2,3,4],[5,6,7,8]])
a2d

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [115]:
np.dsplit(a2d,2)

ValueError: dsplit only works on arrays of 3 or more dimensions

np.dsplit only works on 3-d or higher dimension arrays. np.split can be used to split 1-d or 2-d arrays into sub-arrays

In [116]:
np.split(a2d,2)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

Both the dsplit and split function can be used to split the arrays into multiple sub-arrays of equal size. If the arrays are of unequal size we get error.

In [117]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anithabhukya/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anithabhukya/numpy-array-operations


'https://jovian.ai/anithabhukya/numpy-array-operations'

## Function 4 - linalg.eig(array)

Compute the eigenvalues and right eigenvectors of a square array.

In [118]:
from numpy import linalg as la

In [119]:
# Example 1 - working
a2 = np.random.randint(1,10,size = (3,3))
a2

array([[9, 4, 9],
       [5, 5, 9],
       [2, 9, 4]])

In [120]:
la.eig(a2)

(array([18.2599656 ,  3.51280906, -3.77277466]),
 array([[-0.68673478, -0.87315056, -0.3482674 ],
        [-0.5673716 ,  0.16928904, -0.56717616],
        [-0.454406  ,  0.45710974,  0.74633841]]))

In [121]:
la.eigvals(a2)

array([18.2599656 ,  3.51280906, -3.77277466])

In the above example eigenvalues of a 2-D array are calculated using linalg.eig and linalg.eigvals.

In [122]:
# Example 2 - working
a3 = np.random.randint(1,10,size = (2,2,2))
a3

array([[[8, 7],
        [8, 1]],

       [[4, 7],
        [9, 4]]])

In [123]:
la.eig(a3)

(array([[12.76135582, -3.76135582],
        [11.93725393, -3.93725393]]),
 array([[[ 0.82685203, -0.51144032],
         [ 0.56241953,  0.8593188 ]],
 
        [[ 0.66143783, -0.66143783],
         [ 0.75      ,  0.75      ]]]))

In [124]:
la.eigvals(a3)

array([[12.76135582, -3.76135582],
       [11.93725393, -3.93725393]])

Eigenvalues are calculated for a 3-D arrays.

In [125]:
# Example 3 - breaking (to illustrate when it breaks)
a1 = np.random.randint(1,10,size = (4))
a1

array([6, 7, 5, 6])

In [126]:
la.eig(a1)

LinAlgError: 1-dimensional array given. Array must be at least two-dimensional

In [127]:
a2u = np.random.randint(1,10,size = (3,4))
a2u

array([[4, 8, 5, 3],
       [6, 7, 1, 8],
       [5, 5, 6, 5]])

In [128]:
la.eig(a2u)

LinAlgError: Last 2 dimensions of the array must be square

The above example gives error because eigen values can be calculated on 2-D and above and on a square matrix only.

linalg.eig can be used to compute the eigenvalues and right eigenvectors of a square array.

In [129]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anithabhukya/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anithabhukya/numpy-array-operations


'https://jovian.ai/anithabhukya/numpy-array-operations'

## Function 5 - np.arange(start,stop,step)

Return evenly spaced values within a given interval.

In [130]:
# Example 1 - working
range1 = np.arange(1,10)
range1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In the above example we have created a sequence of numbers ranging from 1 to 10

In [131]:
# Example 2 - working
range2 = np.arange(-50,100,10)
range2

array([-50, -40, -30, -20, -10,   0,  10,  20,  30,  40,  50,  60,  70,
        80,  90])

In the above example we have created a sequence of numbers ranging from 10 10 90 with a difference of 10 between any 2 numbers.

In [132]:
# Example 3 - breaking (to illustrate when it breaks)
range2 = np.arange(10,100,20,(3,3))
range2

TypeError: Cannot interpret '3' as a data type

There is an error in the above example because only 1-D array can be created using this arange function. A matrix or an array cannot be created. The alternative method would be using reshape function along wiith arange function.

In [133]:
range2 = np.arange(10,100,10)
range2.reshape(3,3)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

The above function can be used to create a sequence of numbers ranging from -ve to +ve with equal difference between two numbers

In [134]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anithabhukya/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anithabhukya/numpy-array-operations


'https://jovian.ai/anithabhukya/numpy-array-operations'

## Conclusion

5 functions which can be used in data analysis in python using NumPy module was covered in this topic along with the limitations and alternatives.

The Functions include 

function1 = np.diag(v,k=0)

function2 = np.swapaxes(array,axis1,axis2)

function3 = numpy.dsplit(arrayy, indices_or_sections)

function4 = linalg.eig(array)

function5 = np.arange(start,stop,step)

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* https://numpy.org/
* https://www.geeksforgeeks.org
* https://realpython.com

In [135]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "anithabhukya/numpy-array-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/anithabhukya/numpy-array-operations


'https://jovian.ai/anithabhukya/numpy-array-operations'